# Generated by Django 4.2 on 2023-11-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_directmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessagePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("receiver", models.CharField(max_length=255)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                        ],
                        default="allowed",
                    ),
                ),
            ],
            options={
                "ordering": ("sender",),
            },
        ),
    ]
