# Generated by Django 4.2 on 2023-11-07 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_directmessagepermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directmessagepermission",
            options={"ordering": ("created_at",)},
        ),
        migrations.AddField(
            model_name="directmessagepermission",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
