# Generated by Django 4.2 on 2023-10-30 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 30, 23, 46, 43, 361800, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
