# Generated by Django 4.2 on 2023-10-30 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0002_alter_listing_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 30, 23, 57, 47, 565318, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
