# Generated by Django 4.2 on 2023-11-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0002_user_birth_date_alter_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
