# Generated by Django 4.2 on 2023-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0003_alter_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture_url",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/DefaultProfilePicture.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
