# Generated by Django 4.2 on 2023-10-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0004_alter_listing_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 30, 23, 59, 0, 929057, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="saved_by",
            field=models.ManyToManyField(
                related_name="saved_listings", to="rrapp.rentee"
            ),
        ),
    ]
