# Generated by Django 4.2 on 2023-11-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0004_remove_user_profile_picture_url_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="state",
            field=models.CharField(
                default="New York", max_length=10, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(
                default="New York", max_length=100, verbose_name="City"
            ),
        ),
    ]
