# Generated by Django 4.2 on 2023-11-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0005_listing_state_alter_listing_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_pets",
        ),
        migrations.AddField(
            model_name="user",
            name="food_group",
            field=models.CharField(
                choices=[
                    ("vegan", "Vegan"),
                    ("vegetarian", "Vegetarian"),
                    ("non_vegetarian", "Non Vegetarian"),
                    ("all", "All"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pets",
            field=models.CharField(
                choices=[
                    ("cats", "Cats"),
                    ("dogs", "Dogs"),
                    ("none", "None"),
                    ("all", "All"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
