# Generated by Django 4.2 on 2023-10-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0005_alter_listing_created_at_alter_listing_saved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 30, 23, 59, 6, 395790, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
