# Generated by Django 4.2 on 2023-11-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0006_remove_user_has_pets_user_food_group_user_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="DefaultProfile.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
