# Generated by Django 4.2 on 2023-11-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0006_remove_user_has_pets_user_food_group_user_pets"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
