# Generated by Django 4.2 on 2023-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
