# Generated by Django 4.2 on 2023-10-31 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0007_alter_listing_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentee",
            name="saved_listings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="rrapp.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 31, 14, 26, 27, 587041, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="date_available_from",
            field=models.DateField(default=datetime.date(2023, 10, 31)),
        ),
        migrations.AlterField(
            model_name="listing",
            name="date_available_to",
            field=models.DateField(default=datetime.date(2023, 11, 30)),
        ),
        migrations.AlterField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="rrapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="rentee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentee",
                to="rrapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="renter",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renter",
                to="rrapp.user",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="saved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="rrapp.rentee",
            ),
        ),
    ]
