# Generated by Django 4.2 on 2023-10-31 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0008_rentee_saved_listings_alter_listing_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="saved_by",
        ),
        migrations.RemoveField(
            model_name="rentee",
            name="saved_listings",
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 31, 14, 49, 43, 628357, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="SavedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rentee_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_listing",
                        to="rrapp.rentee",
                    ),
                ),
                (
                    "saved_listings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentee",
                        to="rrapp.listing",
                    ),
                ),
            ],
        ),
    ]
