# Generated by Django 4.2 on 2023-11-13 18:18

from django.db import migrations, models
import django.db.models.deletion
import rrapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0008_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="DefaultProfile.jpg", upload_to="profile_pictures/"
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=rrapp.models.get_uploaded_to
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="rrapp.listing",
                    ),
                ),
            ],
        ),
    ]
