# Generated by Django 4.2 on 2023-11-26 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0011_user_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
