# Generated by Django 4.2 on 2023-12-01 17:08

from django.db import migrations, models
import rrapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0013_rating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=rrapp.models.user_id_directory_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_student",
            field=models.BooleanField(default=False),
        ),
    ]
