# Generated by Django 4.2 on 2023-12-04 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0013_rating_created_at"),
        ("rrapp", "0014_alter_quiz_question2_alter_user_profile_picture"),
    ]

    operations = []
