# Generated by Django 4.2 on 2023-12-04 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0014_listing_restrict_to_matches_alter_quiz_question2_and_more"),
        ("rrapp", "0015_merge_20231203_2328"),
    ]

    operations = []
