# Generated by Django 4.2 on 2023-12-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0018_user_id_picture_user_verified_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
