# Generated by Django 4.2 on 2023-12-05 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0018_alter_quiz_question2_alter_user_profile_picture_and_more"),
        ("rrapp", "0019_user_id_picture_user_verified_student_and_more"),
    ]

    operations = []
