# Generated by Django 4.2 on 2023-12-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0019_alter_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="gender_type",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("All", "All")],
                default="All",
                max_length=20,
            ),
        ),
    ]
