# Generated by Django 4.2 on 2023-12-07 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0020_listing_lease_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="lease_status",
            new_name="lease_type",
        ),
    ]
