# Generated by Django 4.2 on 2023-12-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0021_rename_lease_status_listing_lease_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Amenities",
        ),
        migrations.DeleteModel(
            name="Preference",
        ),
        migrations.AddField(
            model_name="listing",
            name="preferred_gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non Binary"),
                    ("all", "All"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
