# Generated by Django 4.2 on 2023-12-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0022_delete_amenities_delete_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non Binary"),
                ],
                default="male",
                max_length=20,
            ),
        ),
    ]
