# Generated by Django 4.2 on 2023-12-08 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrapp", "0023_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2033, 12, 5, 19, 56, 1, 281932, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
