# Generated by Django 4.2 on 2023-10-10 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rrapp', '0002_amenities_preference_listing_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 10, 22, 37, 0, 803655, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
